language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: osx, env: PYTHON_VERSION=3.4 }

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda create -n test-environment python=$PYTHON_VERSION --file requirements.txt
  - source activate test-environment
  - pip install -e .

script:
  - python -m pytest
